elastic/elastic-otel-java

.github/workflows/release.yml
The await-maven-artifact job and all its dependents should not depend on the actual release-task:
It is possible that the maven-publish succeeded, but something else was wrong with the workflow (e.g. the GH-release could not be created due to a workflow error).
In that case we'll need to update the workflow and retrigger the release while skipping the maven-central deployment.
This will only work if those follow up jobs don't directly depend on the release job, because otherwise they'll be skipped aswell.
=> Release process: allow skipping maven-publish in case of retriggers of the workflow

.github/workflows/snapshot.yml, licenses/more-licences.md
Looks like the heuristic isn't working properly, in the release workflow we use a warmup, which might explain the difference.
=> Fix snapshot workflow getting confused by other output

.github/workflows/snapshot.yml, agent/build.gradle.kts, build.gradle, buildSrc/src/main/kotlin/elastic-otel.library-packaging-conventions.gradle.kts, buildSrc/src/main/kotlin/elastic-otel.sign-and-publish-conventions.gradle.kts, common/build.gradle.kts, inferred-spans/build.gradle.kts
Closes #151.
Also currently our release was kind of broken: we published `inferred-spans` as a library, but didn't publish the `common` project it depends on.
=> Fix and centralize publishing logic

.github/workflows/build.yml
This has two benefits:
* Allows us to easily introduce a matric-job for testing various JVM versions without always having to recompile
* If the workflow fails, it will be immediately clear if it was due to compilation/checkStyle or tests
Preparation for #180.
=> Split building and testing in workflow

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/test-reporter.yml, README.md, build.gradle, buildSrc/src/main/kotlin/elastic-otel.java-conventions.gradle.kts, buildSrc/src/main/kotlin/elastic-otel.library-packaging-conventions.gradle.kts, buildSrc/src/main/kotlin/elastic-otel.test-with-agent-conventions.gradle.kts, custom/build.gradle.kts, custom/src/test/java/co/elastic/otel/config/ConfigurationExporterTest.java, gradle/libs.versions.toml, inferred-spans/build.gradle.kts, inferred-spans/src/test/java/co/elastic/otel/profiler/CallTreeSpanifyTest.java, inferred-spans/src/test/java/co/elastic/otel/profiler/CallTreeTest.java, inferred-spans/src/test/java/co/elastic/otel/profiler/InferredSpansAutoConfigTest.java, inferred-spans/src/test/java/co/elastic/otel/profiler/SamplingProfilerQueueTest.java, inferred-spans/src/test/java/co/elastic/otel/profiler/SamplingProfilerTest.java, inferred-spans/src/test/java/co/elastic/otel/profiler/ThreadMatcherTest.java, inferred-spans/src/test/java/co/elastic/otel/profiler/asyncprofiler/AsyncProfilerTest.java, inferred-spans/src/test/java/co/elastic/otel/profiler/asyncprofiler/JfrParserTest.java, jvmti-access/build.gradle.kts, jvmti-access/src/test/java/co/elastic/otel/ResourceExtractionUtilTest.java, jvmti-access/src/test/java/co/elastic/otel/UniversalProfilingCorrelationTest.java, settings.gradle.kts, smoke-tests/build.gradle, testing-common/src/main/java/co/elastic/otel/testing/DisabledOnOpenJ9.java, testing-common/src/main/java/co/elastic/otel/testing/DisabledOnOpenJ9Condition.java, testing/integration-tests/inferred-spans-test/src/test/java/InferredSpansTest.java, universal-profiling-integration/build.gradle.kts
Closes #180 .
I've intentionally used the same approach and property names like the upstream agent, so that we don't get confused when working on both:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/9d94b4fd7e5ebcf227e29a6d4e1c343621c46438/conventions/src/main/kotlin/otel.java-conventions.gradle.kts#L375
=> Allow testing for different JVM versions and implementations

.github/workflows/build.yml
Looks like #187 broke the test reporting workflow:
```
Error: Response code 400 (Authentication information is not given in the correct format. Check the value of Authorization header.)
```
https://github.com/elastic/elastic-otel-java/actions/runs/8453636169/job/23156761898#step:2:42
I assume it is due to the change of the `upload-artifact` action from `@v3` to `@v4`.
=> Fix test reporting

jvmti-access/src/main/java/co/elastic/otel/profiler/MessageDecoder.java, jvmti-access/src/main/java/co/elastic/otel/profiler/ProfilerRegistrationMessage.java, jvmti-access/src/test/java/co/elastic/otel/UniversalProfilingCorrelationTest.java
Implements the decoding for the new [universal profiler registration message](https://github.com/elastic/apm/blob/main/specs/agents/universal-profiling-integration.md#profiler-registration-message).
This PR only implements the deserialization, our extension won't do anything with this message yet.
=> Implemented decoding for profiler registration messages

custom/src/main/java/co/elastic/otel/config/LegacyConfigurations.java
fixes failing build on `main`.
=> add missing legacy config option

universal-profiling-integration/src/main/java/co/elastic/otel/SpanProfilingSamplesCorrelator.java, universal-profiling-integration/src/main/java/co/elastic/otel/UniversalProfilingProcessor.java, universal-profiling-integration/src/main/java/co/elastic/otel/UniversalProfilingProcessorBuilder.java, universal-profiling-integration/src/main/java/co/elastic/otel/hostid/ProfilerHostIdApplyingSpanExporter.java, universal-profiling-integration/src/main/java/co/elastic/otel/hostid/ProfilerHostIdResourceUpdater.java, universal-profiling-integration/src/main/java/co/elastic/otel/hostid/ProfilerProvidedHostId.java, universal-profiling-integration/src/test/java/co/elastic/otel/UniversalProfilingProcessorTest.java, universal-profiling-integration/src/test/java/co/elastic/otel/hostid/ProfilerHostIdApplyingSpanExporterTest.java
Implements https://github.com/elastic/apm/pull/853:
* If the profiler provides a `host.id` it will be added to the spans
* The profiler can now tell the extension how long to wait for the stacktraces for spans to arrive
* Added option for the extension to remain inactive until a profiler is actually detected
=> Handle profiler registration messages

agentextension/build.gradle.kts, common/src/main/java/co/elastic/otel/common/LocalRootSpan.java, common/src/main/java/co/elastic/otel/common/SpanValueStorageProvider.java, universal-profiling-integration/src/main/java/co/elastic/otel/ProfilerSharedMemoryWriter.java
The release currently failed due to a gradle cautionary check, which is a false-positive in this case:
```
* What went wrong:
Execution failed for task ':agentextension:publishMavenPublicationToSonatypeRepository'.
> Failed to publish publication 'maven' to repository 'sonatype'
> Artifact elastic-otel-agentextension-0.1.0.jar wasn't produced by this build.
```
I've fixed the issue by reusing the same logic for publishing a shadow-jar we use for publishing our distro agent.
Also this PR includes two bug-fixes I forgot about which are also included in #215 . Without those, the agent-extension will not work properly.
=> Fix agentextension publishing and LocalRootSpan bug in agentextension

jvmti-access/build.gradle.kts
These changes should make the binaries safer to use (preventing symbol-clashing) and also make them slightly smaller. Stumbled across this in [this comment](https://github.com/async-profiler/async-profiler/issues/872#issuecomment-1909977286).
=> Hide statically linked libstdc++ symbols and enable compiler to remove unused code.

.buildkite/release.yml, .buildkite/snapshot.yml
Not all the published artifacts were included in the buildkite result, thus this PR fixes that.
Finding which gradle modules/projects needs to be used here is quite straightforward by using the following command:
```
find . -name 'build.gradle.kts'|xargs grep 'sign-and-publish-conventions'|column -t
```
Which here provides:
```
./inferred-spans/build.gradle.kts:  id("elastic-otel.sign-and-publish-conventions")
./common/build.gradle.kts:          id("elastic-otel.sign-and-publish-conventions")
./agentextension/build.gradle.kts:  id("elastic-otel.sign-and-publish-conventions")
./agent/build.gradle.kts:           id("elastic-otel.sign-and-publish-conventions")
```
=> [ci] add missing artifacts in buildkite

.buildkite/release.yml, .buildkite/snapshot.yml, .ci/release.sh, .ci/snapshot.sh, .github/workflows/release.yml, .github/workflows/snapshot.yml
Enable the provenance for the jar file generated in Buildkite using the [GitHub provenance action](https://github.com/github-early-access/generate-build-provenance).
User `artifacts.tar` to store all the artifacts that are produced (uses https://github.com/elastic/elastic-otel-java/pull/226)
I created a test feature branch and triggered the snapshot workflow:
- https://github.com/elastic/elastic-otel-java/actions/runs/8816874378
See https://github.com/elastic/elastic-otel-java/attestations 
Similar to https://github.com/elastic/apm-agent-java/pull/3594
=> github-actions: enable provenance

.github/workflows/release.yml
Automatically create a github release as one of the last steps of the release workflow.
=> [ci] add GH release to release workflow

buildSrc/src/main/kotlin/elastic-otel.library-packaging-conventions.gradle.kts, inferred-spans/build.gradle.kts, inferred-spans/src/main/java/co/elastic/otel/profiler/InferredSpansProcessor.java
Because we publish our extensions as standalone extensions, it theoretically is possible to end up with different versions of the individual libraries on the classpath. Therefore it is useful to log (or somehow expose, e.g. as the tracer version) the exact library version used.
This was already implemented for `inferred-spans` by generating a textual resource containing the version. The way this was implemented was brittle though, as I broke it by removing all other resources while upgrading to async-profiler 3.
This PR makes accessing the version simpler to use by letting gradle generate a java source exposing the project version.
I've added this functionality to our `library-packaging-convetions` to make it available to all our libraries.
=> Generate class exposing version for libraries

jvmti-access/build.gradle.kts
This reverts commit a793f19a64614a5ac229c5c0e6262c92d76a155a.
Unfortunately the changes to the compiler flags caused the universal-profiling host agent to fail at detecting the library. I'll contact the profiling team to investigate the root cause for the detection failure.
=> Revert "Hide statically linked libstdc++ symbols and enable compiler to remove unused code. (#221)"

.github/workflows/release.yml, version.properties
The previous release failed because the `gh release create` was executed before the post-release task published the tag.
This caused the tag to be created by the `gh release create`, making the post-release step fail.
=> Fix release process, manually bump to next snapshot version

universal-profiling-integration/src/test/java/co/elastic/otel/UniversalProfilingProcessorTest.java
There was a rare flake in the test: Sometimes if the timing was correct, the background thread started by the profiling integration would pick up `span1` into the `PeekingPoller`, causing `span3` to fit into the ringbuffer.
=> Fix flakyness of universal profiling integration bufferCapacityExceeded test

common/src/main/java/co/elastic/otel/common/LocalRootSpan.java, testing/integration-tests/inferred-spans-test/build.gradle.kts
Fixes #236.
The reason this was not caught by our integration tests is that for the inferred spans test there was no service-name configured. This in turn caused the universal profiling integration to not be active, which triggers the problematic `LocalRootSpan`.
Configuring the `service.name` in the integration test reproduced the issue.
@jackshirazi would still be great if you could do a quick manual test in your scenario where you uncovered the problem to make sure nothing else breaks.
=> Fix ClassCastException in inferred spans

.github/workflows/release.yml, .github/workflows/snapshot.yml
Use GitHub secrets to run the Buildkite release/snapshot and notify status in Slack.
No more Vault secrets access. 
There is a pending task to replace the GitHub token user.
I created a feature branch called `test/buildkite-tokens` and ran:
- https://github.com/elastic/elastic-otel-java/actions/runs/9365639057
=> github-action: run buildkite action with GH secrets and slack notifications

inferred-spans/src/main/java/co/elastic/otel/profiler/ProfilingActivationListener.java, inferred-spans/src/test/java/co/elastic/otel/profiler/SamplingProfilerTest.java
Closes #250.
Activations of remote spans wil lbe effectively ignored:
* If a remote span is activated as first span on a thread (typical case), it won't start a profiling session. Only when an actual server-span (child of the remote span) is started, the profiling will be started.
* If a remote span is activated while a profiling session is already active (=it replace a local span), this activation is effectively ignored. This means inferred spans on the given thread will continue to be children of the previously active span.
@AlexanderWert you observed some strange behaviour of invalid parent/child relationships with a GRPC use-case. Would be great if you find the time to check with the snapshot from this PR if it fixes the issue.
=> Fix handling of remote spans for inferred spans

.github/workflows/README.md, .github/workflows/pre-post-release.yml, .github/workflows/release-step-1.yml, .github/workflows/release-step-3.yml, .github/workflows/release.yml
- **rename step 1**
- **add PR title and body arguments**
- **rename step 3**
- **clarify project version check**
- **update readme about the release process**
=> [release] improve release steps naming 

buildSrc/src/main/kotlin/elastic-otel.java-conventions.gradle.kts, testing/integration-tests/inferred-spans-test/build.gradle.kts, testing/integration-tests/inferred-spans-test/src/test/java/InferredSpansTest.java
The integration tests for inferred-spans would occasionally crash for openJ9: OpenJ9 support is experimental in async-profiler and seems to be a bit racy, making the JVM crash sometimes.
[here](https://github.com/elastic/elastic-otel-java/actions/runs/9642043462/job/26589205481) is an example of such a failed run. 
For that we reason, we already exclude openj9 from async-profiler tests. For the integration tests, the `@DisabledOnOpenj9` annotation isn't sufficient though, because there we start the agent via JVM parameters, which potentially can already crash the JVM before JUnit even gets to run.
This PR adds a config option to gradle to exclude projects from running with openJ9 for tests.
=> Fix disabling of inferred spans tests with openJ9

custom/src/main/java/co/elastic/otel/SpanStackTraceProcessorAutoConfig.java, custom/src/test/java/co/elastic/otel/SpanStackTraceProcessorAutoConfigTest.java, testing-common/src/main/java/co/elastic/otel/testing/AutoConfiguredDataCapture.java
Currently, we'll always install the processor for adding span stacktraces. This PR allows users to fully disable the feature by providing a negative min-duration.
This is especially relevant for our benchmarks where we want to test features in isolation.
=> Allow full disabling of the span-stacktrace feature

inferred-spans/src/main/java/co/elastic/otel/profiler/SamplingProfiler.java, inferred-spans/src/test/java/co/elastic/otel/profiler/SamplingProfilerTest.java
We had a user report that the `inferred-spans` feature fails to generate spans even though it should.
After analyzing the diagnostic files, turns out that the profiling data was using a different clock than `System.nanoTime`, which is required for correlation.
Async-profiler 3.0 by default tries to use `TSC` only falls back to `System.nanoTime` if `TSC` is not available on the current CPU/System. The `clock=m` startup argument should force the monotonic clock (=`System.nanoTime`) to be always used.
=> Force monotonic clock when starting async-profiler

jvmti-access/build.gradle.kts, jvmti-access/jni-build/jni_linux_musl_arm64.Dockerfile, jvmti-access/jni-build/jni_linux_musl_x64.Dockerfile, jvmti-access/src/main/java/co/elastic/otel/JvmtiAccess.java, jvmti-access/src/main/jni/ProfilerSocket.cpp
Fixes #228 , but needs some more investigation:
It looks like the UP integration is partly broken on musl. The profiling data will contain the service name, but the trace/span-id correlation seems to not work.
=> Added portable musl build for jvmti-library

custom/src/main/java/co/elastic/otel/config/LegacyConfigurations.java
so that the legacy options check succeeds
=> add capture_http_client_request_body_size option

.github/dependabot.yml, .github/workflows/labeler.yml
Disable the community issue/PR labeles for renovate PRs and reconfigure dependabot to not receive duplicate PRs
=> Don't label renovate PRs and disable dependabot for java deps

gradle/libs.versions.toml
Renovate complained about the spotless plugin dependency declaration being invalid.
Removed it and the build still works, so it is unused. Looks like just the `spotlessPlugin` dependency is used.
=> Remove unused and invalid spotless dependency declaration

build.gradle.kts
Fixes the publishing accidentally broken by #366. After merging #366, the snapshot build failed because the nexus publishing plugin was missing.
=> Add back accidentally removed nexus publishing plugin

buildSrc/src/main/kotlin/elastic-otel.java-conventions.gradle.kts, common/build.gradle.kts, custom/build.gradle.kts, inferred-spans/build.gradle.kts, jvmti-access/build.gradle.kts, resources/build.gradle.kts, testing-common/build.gradle.kts, universal-profiling-integration/build.gradle.kts
Keeps the dependency declarations of the individual projects less cluttered
=> DRY: Move autoservice and common test dependencies to convention

docs/configure.md
Adding the full set of config options that are additional or have different defaults from the upstream OpenTelemetry agent
=> add specific config options to config doc

README.md, custom/breakdown-metrics.md, custom/src/main/java/co/elastic/otel/ElasticAgentListener.java, custom/src/main/java/co/elastic/otel/ElasticAutoConfigurationCustomizerProvider.java, custom/src/main/java/co/elastic/otel/ElasticBreakdownMetrics.java, custom/src/main/java/co/elastic/otel/ElasticExtension.java, smoke-tests/src/test/java/com/example/javaagent/smoketest/AgentFeaturesSmokeTest.java, testing/integration-tests/universal-profiling-test/build.gradle.kts
Fixes https://github.com/elastic/elastic-otel-java/issues/383 by disabling the feature.
Removes feature mention and ingest pipeline from readme (part of #254)
=> pull the plug on breakdown metrics

.github/workflows/build.yml
The test-reporter.yml workflow, which consumes these artifacts, is currently disabled.
The fix for the test-reporter will be handled in a follow-up.
=> Bump upload-artifact to v4

.github/workflows/pre-post-release.yml
Use the GitHub app to generate the required ephemeral tokens with the least permissive principle.
* Finer-grained tokens with Service Machine accounts are required to rotate the secrets manually.
* GitHub app to generate temporary tokens is the advanced approach to avoid the above
* Document what the GH workflow requires to run in terms of access
* GitHub Token with Permissions does not trigger GitHub builds 
Use `tibdex/github-app-token` with the required permissions and the repository scope
Remove the `permissions` configuration in the GH workflow.
Configure git checkout with the ephemeral token
Configure the GH_TOKEN with the ephemeral token
=> ci: use GitHub app for ephemeral tokens

universal-profiling-integration/build.gradle.kts
There is currently a problem when using the universal-profling-integration with manual SDK setup:
The type `UniversalProfilingProcessor` cannot be used because it's supertype `AbstractChainingSpanProcessor` is missing. The latter comes from our `common` project as a transitive dependency which is only pulled in with `runtime` scope.
This PR fixes this ensuring that the type is available at compile time too.
A workaround for now is to add an explicit dependency on the `elastic-otel-java:common` project in client code.
=> Fix missing transitive dependencies when using universal profiling integration

custom/src/main/java/co/elastic/otel/SpanStackTraceProcessorAutoConfig.java, custom/src/test/java/co/elastic/otel/SpanStackTraceProcessorAutoConfigTest.java
The hyphen in the config option makes it impossible to specify the option via environment variables.
=> Remove illegal hyphen in span stacktrace config option

custom/src/main/java/co/elastic/otel/ElasticAutoConfigurationCustomizerProvider.java, custom/src/main/java/co/elastic/otel/config/DynamicInstrumentation.java, custom/src/test/java/co/elastic/otel/config/DynamicInstrumentationTest.java, smoke-tests/src/test/java/com/example/javaagent/smoketest/DynamicInstrumentationSmokeTest.java, smoke-tests/test-app/src/main/java/co/elastic/otel/test/DynamicInstrumentationController.java
The trace scoping in the SDK is still experimental at this point, so the relevant methods are non-public, hence the use of reflection to access them. Also, dynamically changing scope enablement is additionally experimental with the only additional support in SdkTracer.tracerEnabled being mutable (non-final). As it turns out, this is all that is needed to enable dynamically disabling instrumentation by scope, using reflection.
=> add dynamically disabled instrumentation capability

custom/src/main/java/co/elastic/otel/config/DynamicInstrumentation.java, smoke-tests/src/test/java/com/example/javaagent/smoketest/DynamicInstrumentationSmokeTest.java, smoke-tests/test-app/src/main/java/co/elastic/otel/test/DynamicInstrumentationController.java
A special instrumentation called `_ALL_` when disabled set the instrumentation scope to disabled for ALL tracers
=> add disable all instrumentations option

renovate.json, smoke-tests/src/test/java/com/example/javaagent/smoketest/DynamicConfigSmokeTest.java
We don't have any CI checks on the examples, so we don't want unverified version bumps.
=> Renovate: Ignore examples folder

examples/openai/build.gradle.kts, examples/openai/src/main/java/openai/example/Chat.java, gradle/libs.versions.toml, instrumentation/openai-client-instrumentation/src/main/java/co/elastic/otel/openai/wrappers/ChatCompletionEventsHelper.java, instrumentation/openai-client-instrumentation/src/main/java/co/elastic/otel/openai/wrappers/InstrumentedChatCompletionService.java, instrumentation/openai-client-instrumentation/src/test/java/co/elastic/otel/openai/ChatTest.java, instrumentation/openai-client-instrumentation/src/test/java/co/elastic/otel/openai/LiveAPIChatIntegrationTest.java
changes in the API are in the latest 0.13.0 version from [this issue](https://github.com/openai/openai-java/issues/53#issuecomment-2607619117)
Notes:
* `type()` -> `_type()` was an intentional change
* fields we set before which can be inferred are now automatically set.
=> deps: updates openai to latest and adjusts example

docs/configure.md
Clarifies that the OpenAI client instrumentation is in tech preview because the client itself is still beta and therefore will often have breaking changes.
This will allow us to clean up and remove (and therefore not maintain) all the compatibility code for the breaking changes during beta eventually.
=> Replace experimental with tech preview for the OpenAI client instrumentation, clarify reasoning

docs/configure.md
- document that micrometer metrics are disabled by default
- add configuration option to enable them
- add link to the other related options for micrometer metrics to otel conversion (in the upstream instrumentation).
=> document micrometer metrics

CHANGELOG.next-release.md, gradle/libs.versions.toml, instrumentation/openai-client-instrumentation/common/src/main/java/co/elastic/otel/openai/wrappers/EventLoggingStreamedResponse.java, instrumentation/openai-client-instrumentation/common/src/main/java/co/elastic/otel/openai/wrappers/InstrumentedChatCompletionService.java, instrumentation/openai-client-instrumentation/common/src/main/java/co/elastic/otel/openai/wrappers/InstrumentedChatService.java, instrumentation/openai-client-instrumentation/common/src/main/java/co/elastic/otel/openai/wrappers/InstrumentedEmbeddingsService.java, instrumentation/openai-client-instrumentation/common/src/main/java/co/elastic/otel/openai/wrappers/InstrumentedOpenAiClient.java, instrumentation/openai-client-instrumentation/common/src/main/java/co/elastic/otel/openai/wrappers/TracingStreamedResponse.java, instrumentation/openai-client-instrumentation/instrumentation-0.14/src/main/java/co/elastic/otel/openai/v0_14/OpenAiClientInstrumentationModule.java
These versions
* added some new methods in the chat-completion and embeddings API which we don't trace for now, but therefore require dynamic proxying
* removed the `Exception` from the `close()` signature, which fortunately for us is a bytecode-backwards compatible change
I don't think we need to check and add those new methods to our instrumentation now, we should revisit when the OpenAI client is out of beta. Currently there are almost weekly releases changing things, which would just cause too much of an overhead for us.
=> Add support for OpenAI client 0.22 to 0.31

testing/integration-tests/inferred-spans-test/src/test/java/InferredSpansTest.java
Got the problem of tests crashing on Java 23 quite frequently now, so let's disable them there until a new async-profiler version is released and in.
=> Disable flaky inferred spans test on Java 23 for now

CHANGELOG.next-release.md, README.md, custom/src/main/java/co/elastic/otel/ElasticAutoConfigurationCustomizerProvider.java, custom/src/test/java/co/elastic/otel/ElasticAutoConfigurationCustomizerProviderTest.java
Closes #446 .
I've manually verified that this change is backwards-compatible for our existing Kibana Dashboards: The runtime-metrics dashboard currently available when ingesting OTLP via apm-server only uses gauges and up-down-counters, which are not affected by this temporality change.
=> Change default metric temporality to delta

.github/dependabot.yml
I've just discovered the reusable composite actions were not actually taking into account with dependabot
=> dependabot: for github actions and composite actions

CHANGELOG.next-release.md, custom/build.gradle.kts, custom/src/main/java/co/elastic/otel/ElasticUserAgentHeader.java, custom/src/test/java/co/elastic/otel/ElasticAutoConfigurationCustomizerProviderTest.java, testing-common/src/main/java/co/elastic/otel/testing/OtelReflectionUtils.java
Just after releasing, I discovered that the temporality setting `otel.exporter.otlp.metrics.temporality.preference` had no more effect. The temporality would always be cumulative, independent of what is configured. Even our changed default to delta did not take effect.
This was introduced in #593 due to a bug in the `toBuilder()` implementation in the exporters:
https://github.com/open-telemetry/opentelemetry-java/issues/7276
I've added more integrationish test reproducing the problem and added a workaround. I've also manually verified the fix.
=> Workaround for temporality configuration not being possible

.github/workflows/labeler.yml
See https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request
Otherwise, https://github.com/elastic/elastic-otel-java/pull/633/checks#step:8:21
```
Run project_id=$(gh api graphql -f query='query($org:String!,$project_number:Int!){ organization(login:$org){ projectV2(number:$project_number) { id } } }' -F project_number="${PROJECT_NUMBER_ID}" -F org="${ORG}" --jq '.data.organization.projectV2.id' )
project_id=$(gh api graphql -f query='query($org:String!,$project_number:Int!){ organization(login:$org){ projectV2(number:$project_number) { id } } }' -F project_number="${PROJECT_NUMBER_ID}" -F org="${ORG}" --jq '.data.organization.projectV2.id' )
item_id=$(gh project item-add "${PROJECT_NUMBER_ID}" --url "${ITEM_URL}" --owner "${ORG}" --format json --jq .id)
echo …
```
=> github-actions(labeller): add required permissions

smoke-tests/src/test/java/com/example/javaagent/smoketest/UserAgentHeaderTest.java
Workaround for https://github.com/open-telemetry/opentelemetry-java/issues/7354, should only affect and fix the flaky smoke test since the last upgrade of the upstream SDK version (#641).
=> Workaround for upstream bug triggering nested autoconfiguration

custom/src/main/java/co/elastic/otel/dynamicconfig/DynamicConfiguration.java, custom/src/main/java/co/elastic/otel/dynamicconfig/DynamicConfigurationPropertyChecker.java
This was previously only needed in the test loop, but the central config will send a list of instrumentations and this needs to be handled in the dynamic config class the same way, so I'm just moving it across
This is the second PR in a series to get to the agent handling central config, I've broken the full implementation into sections to make it more manageable
=> refactor deactivated instrumentations to be remembered (not just in test)

custom/src/main/java/co/elastic/otel/dynamicconfig/DynamicConfiguration.java
We decided to provide per signal send_* config options in central config instead of just one global send, so we need those in teh dynamic config API
=> Align dynamic config API to kibana send* config options

custom/src/main/java/co/elastic/otel/ElasticAutoConfigurationCustomizerProvider.java, custom/src/main/java/co/elastic/otel/dynamicconfig/CentralConfig.java, custom/src/main/java/co/elastic/otel/dynamicconfig/DynamicConfiguration.java, custom/src/main/java/co/elastic/otel/dynamicconfig/DynamicInstrumentation.java, internal-logging/src/main/java/co/elastic/otel/logging/AgentLog.java
Mainly adding and activating a new CentralConfig class, plus a little refactoring to align method names to option names. No test of the CentralConfig class in this PR, I'll do that in a followup. This is almost the last PR in the sequence to get central config working and integrated to dynamic config, the only thing left is that test and some additional work around property/env var names for the new functionality
=> connect opamp to dynamic config

custom/src/main/java/co/elastic/otel/dynamicconfig/CentralConfig.java
Aligning to decision that OpAMP is off by default but is enabled if elastic.otel.opamp.endpoint(or the equivalent env var) is defined, and that the "/v1/opamp" path is optional, so will be auto-added if not there
=> only elastic.otel.opamp.endpoint or env var are required

custom/src/main/java/co/elastic/otel/dynamicconfig/CentralConfig.java, opamp/src/main/java/co/elastic/opamp/client/CentralConfigurationManagerImpl.java, opamp/src/main/java/co/elastic/opamp/client/OpampClientBuilder.java
The APM UI has central config defined by service name and environment, no environment is equivalent to "All" environments (which is an option for defining the central config). The collector OpAMP extension uses the semconv standard `deployment.environment.name` to determine the environment. 
The value for environments before semconv stabilized was `deployment.environment` and this is still widely used.
The `deployment.environment.name` (or the old key) is a resource attribute.
The PR handles this combo of things
=> Add environment to OpAMP details

opamp/src/main/java/co/elastic/opamp/client/CentralConfigurationManagerImpl.java, opamp/src/test/java/co/elastic/opamp/client/CentralConfigurationManagerTest.java
Already present in collector main, and tested using 9.1 snapshots of agent, collector and cloud
=> Change the opamp document key used to 'elastic'

.github/workflows/labeler.yml
Remove stale automatic comment for community PRs as it's not relevant anymore and the priority is not reflected anymore in the labels.
Also, we currently receive less community PRs than we used to, hence making it less useful.
With this change, the `.github/workflows/labeler.yml` file becomes identical to the one in this PR:
- https://github.com/elastic/apm-agent-java/pull/4114
=> remove community PR comment

opamp/src/main/java/co/elastic/opamp/client/CentralConfigurationManagerImpl.java, opamp/src/main/java/co/elastic/opamp/client/OpampClient.java, opamp/src/main/java/co/elastic/opamp/client/internal/OpampClientImpl.java, opamp/src/main/java/co/elastic/opamp/client/request/delay/VariablePeriodicDelay.java, opamp/src/main/java/co/elastic/opamp/client/request/service/HttpRequestService.java, opamp/src/main/java/co/elastic/opamp/client/request/service/RequestService.java, opamp/src/main/java/co/elastic/opamp/client/request/service/WebSocketRequestService.java, opamp/src/test/java/co/elastic/opamp/client/internal/OpampClientImplTest.java, opamp/src/test/java/co/elastic/opamp/client/request/service/HttpRequestServiceTest.java
I tried merging in the upstream proposed contrib but there were too many changes to make it feasible for now. So I've stuck with a simpler approach. PR includes 3 things
1.  Making HttpRequestService call onConnectionFailed on any request exception
2. Adding an exponential backoff to HttpRequestService which uses the existing retry capability
3. Propagating the current delay through the callback failure methods so that it can be used in the log message
Most of the changes are because of the extra parameter needed for propagating the delay
=> add exponential backoff

custom/src/main/java/co/elastic/otel/ElasticAutoConfigurationCustomizerProvider.java, internal-logging/build.gradle.kts, internal-logging/src/main/java/co/elastic/otel/logging/AgentLog.java, internal-logging/src/main/java/co/elastic/otel/logging/ElasticLoggingCustomizer.java
With the upstream otel agent, when the `otel.javaagent.debug` option is set to `true`, an additional span logging exporter is added when there is none, that means spans start/and are logged at `INFO` level when `otel.javaagent.debug` is set to `true`.
Our current implementation of dynamic log level does currently replicates this behavior, which means that when the dynamic log level is set to `DEBUG` the resulting behavior is not exactly equivalent to setting `otel.javaagent.debug=true` with the upstream agent.
This PR replicates this behavior by doing the following:
- when an logging exporter is already configured, we let the configured one log the spans, which means span logging will happen whenever log level is `INFO` or above.
- when no logging exporter is configured, we add a …
=> implement spans debug logging

.github/CODEOWNERS
Add `@elastic/apm-agent-java` for docs in addition to `@elastic/ingest-docs` to allow devs to review and approve PRs that change both docs and code without needing separate reviews from both dev and docs teams.
=> add dev for docs review

build.gradle.kts
Should hopefully be good enough:
https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#getting-started-for-maven-api-like-plugins
I ran this [Buildkite build](https://buildkite.com/elastic/elastic-otel-java-snapshot/builds/563) [Only Elastic employees can access]
=> Update publish URLS to sonatype central

.github/workflows/gradle-goal/action.yml, .github/workflows/pre-post-release.yml, .github/workflows/validate-tag/action.yml
Update GH workflows and actions to fix the run-shell-injection vulnerability.
More info: https://semgrep.dev/r?q=yaml.github-actions.security.run-shell-injection.run-shell-injection
Tested in personal fork:
- https://github.com/oakrizan/elastic-otel-java/actions/runs/16806426452/job/47599943213
- https://github.com/oakrizan/elastic-otel-java/actions/runs/16806417947/job/47599903022?pr=1
=> ci: fix semgrep reported run-shell-injection

custom/src/test/java/co/elastic/otel/ElasticAutoConfigurationCustomizerProviderTest.java, docs/release-notes/breaking-changes.md, gradle/libs.versions.toml, instrumentation/openai-client-instrumentation/instrumentation-1.1/src/main/java/co/elastic/otel/openai/v1_1/OpenAiClientInstrumentationModule.java, instrumentation/openai-client-instrumentation/instrumentation-1.1/src/test/java/co/elastic/otel/openai/v1_1/ChatTest.java, instrumentation/openai-client-instrumentation/instrumentation-1.1/src/test/java/co/elastic/otel/openai/v1_1/EmbeddingsTest.java
upstream agent now 2.18.1 (needs some small internal test changes)
this distributions openai-client is turned off, leaving the upstream openai instrumentation to do the work (needed a couple of tests disabled)
=> switch to 2.18.1, and switch openai to upstream

custom/src/main/java/co/elastic/otel/ElasticAutoConfigurationCustomizerProvider.java, custom/src/main/java/co/elastic/otel/dynamicconfig/CentralConfig.java
Hooking up https://github.com/elastic/elastic-otel-java/pull/777 to https://github.com/elastic/kibana/pull/231835 for sampling
=> Hook up sampler

docs/reference/edot-java/configuration.md
Contributes to https://github.com/elastic/opentelemetry-dev/issues/992
=> Add 9.2 supported dynamic config options
