elastic/elastic-otel-java

.github/workflows/snapshot.yml
licenses/more-licences.md

Fix snapshot workflow attempt #2

---

gradle/update-upstream.sh

Fix regex for mac.
Needs validation from @JonasKunz on a mac.

fix update script regex

---

version.properties

pre release v0.1.0

---

version.properties

post release v0.1.0

---

version.properties

pre release v0.3.0

---

version.properties

post release v0.3.0

---

version.properties

pre release v0.3.1

---

universal-profiling-integration/src/main/java/co/elastic/otel/UniversalProfilingProcessorAutoConfig.java
universal-profiling-integration/src/test/java/co/elastic/otel/UniversalProfilingProcessorAutoConfigTest.java

The universal profiling integration is enabled by default in "auto" mode.
At the same time, if any exception occurs during the initialization, it will cause the entire agent to not start.
Below is an example of trying to start the agent in a currently unsupported musl distro:
```
[otel.javaagent 2024-05-08 08:29:42:799 +0000] [main] ERROR co.elastic.otel.JvmtiAccess - Failed to load jvmti native library
java.lang.UnsatisfiedLinkError: /tmp/elastic-jvmti-linux-arm64-4813494d137e1631bba301d5acab6e7b-bae36f7120da3a04c6a4554a71f84f1e.so: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/elastic-jvmti-linux-arm64-4813494d137e1631bba301d5acab6e7b-bae36f7120da3a04c6a4554a71f84f1e.so)
at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
at …
```

Crash only the universal profiling integration and not the agent on failure

---

version.properties

pre release v0.3.2

---

version.properties

post release v0.3.2

---

version.properties

Step 2 of the release process for version 0.4.0: review & merge, then execute 'release-step-3' GH workflow

[release] release-step-2 0.4.0

---

version.properties

Step 4 of the release process for version 0.4.0: review & merge

[release] release-step-4 0.4.0

---

.github/workflows/release-step-3.yml
testing-common/src/main/java/co/elastic/otel/testing/DisabledOnOpenJ9Condition.java

docker build was in the wrong place

fix ordering of release action

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/Flaky_test.md
.github/ISSUE_TEMPLATE/Question.md
.github/workflows/labeler.yml

issue template plus labels for triage, community, team

copy issue management from apm-agent-java

---

custom/src/main/java/co/elastic/otel/config/LegacyConfigurations.java
docs/configure.mdx

closes https://github.com/elastic/elastic-otel-java/issues/302

add config redirect for global-labels

---

.github/workflows/release-step-3.yml
.github/workflows/snapshot.yml

Use `v1` - we own it and we use semver
Generate docker containers with multi-platform support

feat: make published Docker images multi-platform, add linux/arm64 plat

---

.github/workflows/release-step-3.yml

ci: missing version

---

version.properties

Step 2 of the release process for version 0.5.0: review & merge, then execute 'release-step-3' GH workflow

[release] release-step-2 0.5.0

---

version.properties

Step 4 of the release process for version 0.5.0: review & merge

[release] release-step-4 0.5.0

---

gradle/libs.versions.toml

@elastic/apm-agent-java, can you please check and merge this PR?
---
<Actions>
<action id="2370090022548352370298855724627f7945c7d64a355c6c7d1221ca3289fcc7">
<h3>Upgrade the upstream agent version and related transitive dependencies</h3>
<details id="41b45edc3907becee9cae4a071a858464f937f92ff671f5cd789a0542d6b8f6b">
<summary>Update upstream OpenTelemetry agent version and related dependencies</summary>
<p>ran shell command &#34;gradle/update-upstream.sh v2.6.0 &amp;&amp; echo \&#34;Update successful\&#34;&#34;</p>
</details>
<a href="https://github.com/elastic/elastic-otel-java/actions/runs/10302967969">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
<td width="77">
</td>
<td>
<p>
Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
</p> …

Update upstream OpenTelemetry agent dependencies to 2.6.0

---

gradle/libs.versions.toml

@elastic/apm-agent-java, can you please check and merge this PR?
---
<Actions>
<action id="2370090022548352370298855724627f7945c7d64a355c6c7d1221ca3289fcc7">
<h3>Upgrade the upstream agent version and related transitive dependencies</h3>
<details id="41b45edc3907becee9cae4a071a858464f937f92ff671f5cd789a0542d6b8f6b">
<summary>Update upstream OpenTelemetry agent version and related dependencies</summary>
<p>ran shell command &#34;gradle/update-upstream.sh v2.7.0 &amp;&amp; echo \&#34;Update successful\&#34;&#34;</p>
</details>
<a href="https://github.com/elastic/elastic-otel-java/actions/runs/10430039132">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
<td width="77">
</td>
<td>
<p>
Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
</p> …

Update upstream OpenTelemetry agent dependencies to 2.7.0

---

README.md
jvmti-access/src/test/java/co/elastic/otel/UniversalProfilingCorrelationTest.java
version.properties

- **bump version for 1.0.0 release**
- **remove warning in readme**

prepare GA release

---

version.properties

Step 2 of the release process for version 1.0.0: review & merge, then execute 'release-step-3' GH workflow

[release] release-step-2 1.0.0

---

version.properties

Step 4 of the release process for version 1.0.0: review & merge

[release] release-step-4 1.0.0

---

gradle/libs.versions.toml

@elastic/apm-agent-java, can you please check and merge this PR?
---
<Actions>
<action id="2370090022548352370298855724627f7945c7d64a355c6c7d1221ca3289fcc7">
<h3>Upgrade the upstream agent version and related transitive dependencies</h3>
<details id="41b45edc3907becee9cae4a071a858464f937f92ff671f5cd789a0542d6b8f6b">
<summary>Update upstream OpenTelemetry agent version and related dependencies</summary>
<p>ran shell command &#34;gradle/update-upstream.sh v2.8.0 &amp;&amp; echo \&#34;Update successful\&#34;&#34;</p>
</details>
<a href="https://github.com/elastic/elastic-otel-java/actions/runs/10860069255">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
<td width="77">
</td>
<td>
<p>
Created automatically by <a href="https://www.updatecli.io/">Updatecli</a>
</p> …

Update upstream OpenTelemetry agent dependencies to 2.8.0

---

.github/workflows/labeler.yml

ci: use gh app ephemeral tokens

---

CHANGELOG.next-release.md

Adds the changelog I forgot to add in #514 before merging.

Add changelog for OpenAI upgrade

---

smoke-tests/src/test/java/com/example/javaagent/smoketest/DynamicConfigSmokeTest.java
smoke-tests/test-app/src/main/java/co/elastic/otel/test/DynamicConfigController.java

Fix DynamicConfigSmokeTest flakyness.

---

instrumentation/openai-client-instrumentation/instrumentation-0.2/build.gradle.kts

Attempts to prevent https://github.com/elastic/elastic-otel-java/pull/533

Prevent renovate from upgrading intentionally fixed openai version

---

CHANGELOG.next-release.md

Adds the changelog I forgot for #539.

Add changelog for OpenAI instrumentation changes

---

custom/src/main/java/co/elastic/otel/dynamicconfig/DynamicConfiguration.java
custom/src/main/java/co/elastic/otel/dynamicconfig/DynamicInstrumentation.java
custom/src/test/java/co/elastic/otel/config/DynamicInstrumentationTest.java
smoke-tests/src/test/java/com/example/javaagent/smoketest/DynamicInstrumentationSmokeTest.java

closes https://github.com/elastic/elastic-otel-java/issues/562

convert dynamic config to use the new SdkTracerProvider.setTracerConfigurator

---

custom/src/test/java/co/elastic/otel/config/DynamicInstrumentationTest.java

forgot to remove these two tests, the methods are no longer used after https://github.com/elastic/elastic-otel-java/pull/565 changes

remove two unused tests

---

opamp/src/main/java/co/elastic/opamp/client/CentralConfigurationManagerImpl.java

add AcceptsRemoteConfig capability

---

gradle/libs.versions.toml
internal-logging/build.gradle.kts

Upgrade log4j2 to 2.25.0

---

docs/release-notes/breaking-changes.md
docs/release-notes/deprecations.md
docs/release-notes/index.md
docs/release-notes/known-issues.md

This adds anchors to existing relnotes headings and fixes the instructions.

Fix anchors and instructions in relnotes

---

.gitignore
docs/configure.md
docs/get-started.md
docs/migrate.md
docs/release-notes/index.md

- Adds artifact folder to .gitignore
- Fixes a link
- Removed old files

Fix link and remove old files

---

custom/src/main/java/co/elastic/otel/dynamicconfig/CentralConfig.java

the parsing needed a fix too, to be consistent with Duration parsing

fix polling interval option to align with UI
